import type { Employee, PayrollParams, Convention, Entreprise } from "./payroll";

// ══════════════════════════════════════════════════════════════════════════════
//  Default Employees — Corrigés selon le fichier Excel source
// ══════════════════════════════════════════════════════════════════════════════
export const DEFAULT_EMPLOYEES: Employee[] = [
  {
    matricule: "IF0001", prenom: "DIEGANE", nom: "BOB", sexe: "M",
    dateNaissance: "1971-12-19", lieuNaissance: "DIOFIOR", nationalite: "Sénégalaise",
    adresse: "Grand Yoff, Maka 2, Dakar", telephone: "(221) 77 249 73 98", email: "",
    situationFamille: "Marié(e)", femmes: 1, enfants: 5,
    fonction: "COMMIS", convention: "COMMERCE", categorie: "3_ème",
    statut: "employés", contrat: "CDI", dateEntree: "2009-01-01",
    salaireBase: 77840, sursalaire: 20104,
    heuresAbsence: 0, heuresAbsMaladie: 0, tauxMaladie: 0, nbPaniers: 0,
    hs115: 0, hs140: 0, hs160: 0, hs200: 0,
    avanceTabaski: 0, avanceCaisse: 0, avanceFinanciere: 0, retCooperative: 0, fraisMedicaux: 0, indKilometrique: 0,
  },
  {
    matricule: "IF0002", prenom: "HELENE AIDA", nom: "MALACK", sexe: "F",
    dateNaissance: "1977-02-27", lieuNaissance: "PIKINE", nationalite: "Sénégalaise",
    adresse: "Sicap Liberté 3, N#1889, Dakar", telephone: "(221) 77 564 38 77", email: "",
    situationFamille: "Marié(e)", femmes: 0, enfants: 3,
    fonction: "SECRETAIRE MEDICALE", convention: "COMMERCE", categorie: "7_ème B",
    statut: "agents de maîtrise", contrat: "CDI", dateEntree: "2009-06-01",
    salaireBase: 113984, sursalaire: 61659,
    heuresAbsence: 0, heuresAbsMaladie: 0, tauxMaladie: 0, nbPaniers: 0,
    hs115: 0, hs140: 0, hs160: 0, hs200: 0,
    avanceTabaski: 0, avanceCaisse: 0, avanceFinanciere: 0, retCooperative: 0, fraisMedicaux: 0, indKilometrique: 0,
  },
];

// ══════════════════════════════════════════════════════════════════════════════
//  Default Parameters — Conforme au fichier Excel
// ══════════════════════════════════════════════════════════════════════════════
export const DEFAULT_PARAMS: PayrollParams = {
  CFCE:      { label: "CFCE",            taux: 0.03,  tauxSalarial: 0,   tauxPatronal: 1,   plafond: null },
  BRS:       { label: "BRS",             taux: 0.05,  tauxSalarial: 1,   tauxPatronal: 0,   plafond: null },
  IPRES_RG:  { label: "IPRES R.G.",      taux: 0.14,  tauxSalarial: 0.4, tauxPatronal: 0.6, plafond: 432000 },
  IPRES_RCC: { label: "IPRES R.C.C.",    taux: 0.06,  tauxSalarial: 0.4, tauxPatronal: 0.6, plafond: 1296000 },
  CSS_AF:    { label: "CSS Alloc. Fam.",  taux: 0.07,  tauxSalarial: 0,   tauxPatronal: 1,   plafond: 63000 },
  CSS_AT:    { label: "CSS Acc. Trav.",   taux: 0.01,  tauxSalarial: 0,   tauxPatronal: 1,   plafond: 63000 },
  IPM:       { label: "IPM",             taux: 0,     tauxSalarial: 0.5, tauxPatronal: 0.5, plafond: null },
  transport: { label: "Ind. Transport",  valeur: 26000 },
};

// ══════════════════════════════════════════════════════════════════════════════
//  Default Entreprise
// ══════════════════════════════════════════════════════════════════════════════
export const DEFAULT_ENTREPRISE: Entreprise = {
  nom: "",
  logo: "",
  adresse: "",
  telephone: "",
  email: "",
  ninea: "",
  rccm: "",
  bulletinTemplate: "classique",
};

// ══════════════════════════════════════════════════════════════════════════════
//  Conventions Collectives — Conformes au fichier Excel
// ══════════════════════════════════════════════════════════════════════════════
export const DEFAULT_CONVENTIONS: Convention[] = [
  {
    id: "CC001", nom: "COMMERCE", secteur: "Commerce général", dateSignature: "1982-01-01",
    description: "Convention collective nationale du commerce applicable au Sénégal.",
    categories: [
      { id: "c1",  code: "1_er A",   libelle: "1ère catégorie A",   statut: "employés",             salaireMinima: 70706 },
      { id: "c2",  code: "1_er B",   libelle: "1ère catégorie B",   statut: "employés",             salaireMinima: 74870 },
      { id: "c3",  code: "2_ème",    libelle: "2ème catégorie",     statut: "employés",             salaireMinima: 75361 },
      { id: "c4",  code: "3_ème",    libelle: "3ème catégorie",     statut: "employés",             salaireMinima: 77840 },
      { id: "c5",  code: "4_ème",    libelle: "4ème catégorie",     statut: "employés",             salaireMinima: 82272 },
      { id: "c6",  code: "5_ème",    libelle: "5ème catégorie",     statut: "employés",             salaireMinima: 89244 },
      { id: "c7",  code: "6_ème",    libelle: "6ème catégorie",     statut: "employés",             salaireMinima: 93790 },
      { id: "c8",  code: "7_ème A",  libelle: "7ème catégorie A",   statut: "agents de maîtrise",   salaireMinima: 105342 },
      { id: "c9",  code: "7_ème B",  libelle: "7ème catégorie B",   statut: "agents de maîtrise",   salaireMinima: 113984 },
      { id: "c10", code: "8_ème A",  libelle: "8ème catégorie A",   statut: "agents de maîtrise",   salaireMinima: 115718 },
      { id: "c11", code: "8_ème B",  libelle: "8ème catégorie B",   statut: "agents de maîtrise",   salaireMinima: 123484 },
      { id: "c12", code: "8_ème C",  libelle: "8ème catégorie C",   statut: "cadres",               salaireMinima: 124254 },
      { id: "c13", code: "9_ème A",  libelle: "9ème catégorie A",   statut: "cadres",               salaireMinima: 125543 },
      { id: "c14", code: "9_ème B",  libelle: "9ème catégorie B",   statut: "cadres",               salaireMinima: 132498 },
      { id: "c15", code: "10_ème A", libelle: "10ème catégorie A",  statut: "cadres",               salaireMinima: 141024 },
      { id: "c16", code: "10_ème B", libelle: "10ème catégorie B",  statut: "cadres",               salaireMinima: 157097 },
      { id: "c17", code: "10_ème C", libelle: "10ème catégorie C",  statut: "cadres",               salaireMinima: 174049 },
      { id: "c18", code: "11_ème",   libelle: "11ème catégorie",    statut: "cadres",               salaireMinima: 195119 },
    ],
  },
  {
    id: "CC002", nom: "INDUSTRIES_ALIMENTAIRES", secteur: "Industries Alimentaires", dateSignature: "1983-06-01",
    description: "Convention collective des industries alimentaires au Sénégal.",
    categories: [
      { id: "ia1",  code: "1ère Ouvriers",  libelle: "1ère Ouvriers",      statut: "ouvriers",             salaireMinima: 64281 },
      { id: "ia2",  code: "2ème Ouvriers",  libelle: "2ème Ouvriers",      statut: "ouvriers",             salaireMinima: 65841 },
      { id: "ia3",  code: "3ème Ouvriers",  libelle: "3ème Ouvriers",      statut: "ouvriers",             salaireMinima: 69009 },
      { id: "ia4",  code: "4ème Ouvriers",  libelle: "4ème Ouvriers",      statut: "ouvriers",             salaireMinima: 72862 },
      { id: "ia5",  code: "5ème Ouvriers",  libelle: "5ème Ouvriers",      statut: "ouvriers",             salaireMinima: 74162 },
      { id: "ia6",  code: "6ème Ouvriers",  libelle: "6ème Ouvriers",      statut: "ouvriers",             salaireMinima: 79870 },
      { id: "ia7",  code: "7ème Ouvriers",  libelle: "7ème Ouvriers",      statut: "ouvriers",             salaireMinima: 85119 },
      { id: "ia8",  code: "1ère Employés",  libelle: "1ère Employés",      statut: "employés",             salaireMinima: 64258 },
      { id: "ia9",  code: "2ème Employés",  libelle: "2ème Employés",      statut: "employés",             salaireMinima: 67272 },
      { id: "ia10", code: "3ème Employés",  libelle: "3ème Employés",      statut: "employés",             salaireMinima: 70426 },
      { id: "ia11", code: "4ème Employés",  libelle: "4ème Employés",      statut: "employés",             salaireMinima: 76721 },
      { id: "ia12", code: "5ème Employés",  libelle: "5ème Employés",      statut: "employés",             salaireMinima: 81936 },
      { id: "ia13", code: "6ème Employés",  libelle: "6ème Employés",      statut: "employés",             salaireMinima: 86436 },
      { id: "ia14", code: "7ème Employés",  libelle: "7ème Employés",      statut: "employés",             salaireMinima: 95679 },
      { id: "ia15", code: "AM0",            libelle: "Agent Maîtrise 0",   statut: "agents de maîtrise",   salaireMinima: 98981 },
      { id: "ia16", code: "AM1",            libelle: "Agent Maîtrise 1",   statut: "agents de maîtrise",   salaireMinima: 102283 },
      { id: "ia17", code: "AM2",            libelle: "Agent Maîtrise 2",   statut: "agents de maîtrise",   salaireMinima: 105585 },
      { id: "ia18", code: "AM3",            libelle: "Agent Maîtrise 3",   statut: "agents de maîtrise",   salaireMinima: 119307 },
      { id: "ia19", code: "AM4",            libelle: "Agent Maîtrise 4",   statut: "agents de maîtrise",   salaireMinima: 131999 },
      { id: "ia20", code: "AM5",            libelle: "Agent Maîtrise 5",   statut: "agents de maîtrise",   salaireMinima: 133096 },
    ],
  },
  {
    id: "CC003", nom: "MECANIQUE_GENERALE", secteur: "Mécanique Générale", dateSignature: "1983-06-01",
    description: "Convention collective de la mécanique générale au Sénégal.",
    categories: [
      { id: "mg1",  code: "1ère M.O",   libelle: "1ère M.O",          statut: "ouvriers",             salaireMinima: 64282 },
      { id: "mg2",  code: "2ème M.S",   libelle: "2ème M.S",          statut: "ouvriers",             salaireMinima: 65829 },
      { id: "mg3",  code: "3ème O.S.1", libelle: "3ème O.S.1",        statut: "ouvriers",             salaireMinima: 69011 },
      { id: "mg4",  code: "4ème O.S.2", libelle: "4ème O.S.2",        statut: "ouvriers",             salaireMinima: 72868 },
      { id: "mg5",  code: "5ème O.P.1", libelle: "5ème O.P.1",        statut: "ouvriers",             salaireMinima: 74201 },
      { id: "mg6",  code: "6ème O.P.2", libelle: "6ème O.P.2",        statut: "ouvriers",             salaireMinima: 80043 },
      { id: "mg7",  code: "7ème O.P.3", libelle: "7ème O.P.3",        statut: "ouvriers",             salaireMinima: 85120 },
      { id: "mg8",  code: "1ère",       libelle: "1ère Employé",      statut: "employés",             salaireMinima: 64262 },
      { id: "mg9",  code: "2ème",       libelle: "2ème Employé",      statut: "employés",             salaireMinima: 67274 },
      { id: "mg10", code: "3ème",       libelle: "3ème Employé",      statut: "employés",             salaireMinima: 70426 },
      { id: "mg11", code: "4ème",       libelle: "4ème Employé",      statut: "employés",             salaireMinima: 76668 },
      { id: "mg12", code: "5ème",       libelle: "5ème Employé",      statut: "employés",             salaireMinima: 81956 },
      { id: "mg13", code: "6ème",       libelle: "6ème Employé",      statut: "employés",             salaireMinima: 86419 },
      { id: "mg14", code: "7ème",       libelle: "7ème Employé",      statut: "employés",             salaireMinima: 95694 },
      { id: "mg15", code: "M.0",        libelle: "Maîtrise 0",       statut: "agents de maîtrise",   salaireMinima: 99027 },
      { id: "mg16", code: "M.1",        libelle: "Maîtrise 1",       statut: "agents de maîtrise",   salaireMinima: 102360 },
      { id: "mg17", code: "M.2",        libelle: "Maîtrise 2",       statut: "agents de maîtrise",   salaireMinima: 105694 },
      { id: "mg18", code: "M.3",        libelle: "Maîtrise 3",       statut: "agents de maîtrise",   salaireMinima: 119337 },
      { id: "mg19", code: "M.4",        libelle: "Maîtrise 4",       statut: "agents de maîtrise",   salaireMinima: 132013 },
      { id: "mg20", code: "M.5",        libelle: "Maîtrise 5",       statut: "agents de maîtrise",   salaireMinima: 133094 },
      { id: "mg21", code: "P1.A",       libelle: "Cadre P1.A",       statut: "cadres",               salaireMinima: 135023 },
      { id: "mg22", code: "P1.B",       libelle: "Cadre P1.B",       statut: "cadres",               salaireMinima: 136952 },
      { id: "mg23", code: "P2.A",       libelle: "Cadre P2.A",       statut: "cadres",               salaireMinima: 138881 },
      { id: "mg24", code: "P2.B",       libelle: "Cadre P2.B",       statut: "cadres",               salaireMinima: 140813 },
      { id: "mg25", code: "P3.A",       libelle: "Cadre P3.A",       statut: "cadres",               salaireMinima: 149728 },
      { id: "mg26", code: "P3.B",       libelle: "Cadre P3.B",       statut: "cadres",               salaireMinima: 211748 },
    ],
  },
  {
    id: "CC004", nom: "PRESTATIONS_DE_SERVICES", secteur: "Prestations de Services", dateSignature: "1990-01-01",
    description: "Convention collective des prestations de services au Sénégal.",
    categories: [
      { id: "ps1", code: "PRESTATION", libelle: "Prestataire de services", statut: "prestataires", salaireMinima: 0 },
    ],
  },
  {
    id: "CC005", nom: "INDUSTRIES_HOTELIERES", secteur: "Hôtellerie & Restauration", dateSignature: "1990-01-01",
    description: "Convention collective des industries hôtelières au Sénégal.",
    categories: [
      { id: "ih1",  code: "1-er",     libelle: "1ère catégorie",    statut: "employés",             salaireMinima: 64282 },
      { id: "ih2",  code: "2-ème",    libelle: "2ème catégorie",    statut: "employés",             salaireMinima: 65208 },
      { id: "ih3",  code: "3-ème",    libelle: "3ème catégorie",    statut: "employés",             salaireMinima: 66371 },
      { id: "ih4",  code: "4-ème",    libelle: "4ème catégorie",    statut: "employés",             salaireMinima: 71100 },
      { id: "ih5",  code: "5-ème",    libelle: "5ème catégorie",    statut: "employés",             salaireMinima: 73046 },
      { id: "ih6",  code: "6-ème A",  libelle: "6ème A",           statut: "employés",             salaireMinima: 77450 },
      { id: "ih7",  code: "6-ème B",  libelle: "6ème B",           statut: "employés",             salaireMinima: 86577 },
      { id: "ih8",  code: "7-ème",    libelle: "7ème catégorie",   statut: "agents de maîtrise",   salaireMinima: 93707 },
      { id: "ih9",  code: "8-ème A",  libelle: "8ème A",           statut: "agents de maîtrise",   salaireMinima: 99516 },
      { id: "ih10", code: "8-ème B",  libelle: "8ème B",           statut: "agents de maîtrise",   salaireMinima: 105569 },
      { id: "ih11", code: "9-ème A",  libelle: "9ème A",           statut: "cadres",               salaireMinima: 110561 },
      { id: "ih12", code: "9-ème B",  libelle: "9ème B",           statut: "cadres",               salaireMinima: 125190 },
      { id: "ih13", code: "10-ème A", libelle: "10ème A",          statut: "cadres",               salaireMinima: 137550 },
      { id: "ih14", code: "10-ème B", libelle: "10ème B",          statut: "cadres",               salaireMinima: 150620 },
      { id: "ih15", code: "11-ème A", libelle: "11ème A",          statut: "cadres",               salaireMinima: 168380 },
      { id: "ih16", code: "11-ème B", libelle: "11ème B",          statut: "cadres",               salaireMinima: 176799 },
    ],
  },
  {
    id: "CC006", nom: "BTP", secteur: "Bâtiment & Travaux Publics", dateSignature: "1985-03-15",
    description: "Convention collective du secteur BTP au Sénégal.",
    categories: [
      { id: "b1",  code: "H1",      libelle: "Manœuvre H1",         statut: "ouvriers",             salaireMinima: 72085 },
      { id: "b2",  code: "H2",      libelle: "Manœuvre H2",         statut: "ouvriers",             salaireMinima: 72425 },
      { id: "b3",  code: "H3",      libelle: "Manœuvre H3",         statut: "ouvriers",             salaireMinima: 77873 },
      { id: "b4",  code: "4 ème A", libelle: "4ème A Ouvrier",      statut: "ouvriers",             salaireMinima: 80022 },
      { id: "b5",  code: "4 ème B", libelle: "4ème B Ouvrier",      statut: "ouvriers",             salaireMinima: 82171 },
      { id: "b6",  code: "5 ème A", libelle: "5ème A Ouvrier",      statut: "ouvriers",             salaireMinima: 83171 },
      { id: "b7",  code: "5 ème B", libelle: "5ème B Ouvrier",      statut: "ouvriers",             salaireMinima: 86557 },
      { id: "b8",  code: "6 ème A", libelle: "6ème A Ouvrier",      statut: "ouvriers",             salaireMinima: 86814 },
      { id: "b9",  code: "6 ème B", libelle: "6ème B Ouvrier",      statut: "ouvriers",             salaireMinima: 96511 },
      { id: "b10", code: "7 ème A", libelle: "7ème A Ouvrier",      statut: "ouvriers",             salaireMinima: 112649 },
      { id: "b11", code: "7 ème B", libelle: "7ème B Ouvrier",      statut: "ouvriers",             salaireMinima: 123157 },
      { id: "b12", code: "1 ère",   libelle: "1ère Employé",        statut: "employés",             salaireMinima: 70697 },
      { id: "b13", code: "2 ème",   libelle: "2ème Employé",        statut: "employés",             salaireMinima: 73989 },
      { id: "b14", code: "3 ème",   libelle: "3ème Employé",        statut: "employés",             salaireMinima: 80642 },
      { id: "b15", code: "4 ème",   libelle: "4ème Employé",        statut: "employés",             salaireMinima: 82096 },
      { id: "b16", code: "5 ème",   libelle: "5ème Employé",        statut: "employés",             salaireMinima: 87564 },
      { id: "b17", code: "6 ème",   libelle: "6ème Employé",        statut: "employés",             salaireMinima: 90926 },
      { id: "b18", code: "7 ème",   libelle: "7ème Employé",        statut: "employés",             salaireMinima: 92861 },
      { id: "b19", code: "AM 1",    libelle: "Agent de Maîtrise 1", statut: "agents de maîtrise",   salaireMinima: 97615 },
      { id: "b20", code: "AM 2",    libelle: "Agent de Maîtrise 2", statut: "agents de maîtrise",   salaireMinima: 114034 },
      { id: "b21", code: "AM 3",    libelle: "Agent de Maîtrise 3", statut: "agents de maîtrise",   salaireMinima: 125290 },
      { id: "b22", code: "AM 4",    libelle: "Agent de Maîtrise 4", statut: "agents de maîtrise",   salaireMinima: 138614 },
      { id: "b23", code: "AM 5",    libelle: "Agent de Maîtrise 5", statut: "agents de maîtrise",   salaireMinima: 139645 },
      { id: "b24", code: "P1A",     libelle: "Cadre P1A",           statut: "cadres",               salaireMinima: 142258 },
      { id: "b25", code: "P1B",     libelle: "Cadre P1B",           statut: "cadres",               salaireMinima: 144873 },
      { id: "b26", code: "P2A",     libelle: "Cadre P2A",           statut: "cadres",               salaireMinima: 158139 },
      { id: "b27", code: "P2B",     libelle: "Cadre P2B",           statut: "cadres",               salaireMinima: 178013 },
      { id: "b28", code: "P3A",     libelle: "Cadre P3A",           statut: "cadres",               salaireMinima: 189340 },
      { id: "b29", code: "P3B",     libelle: "Cadre P3B",           statut: "cadres",               salaireMinima: 268840 },
      { id: "b30", code: "P4",      libelle: "Cadre P4",            statut: "cadres",               salaireMinima: 308589 },
      { id: "b31", code: "P5",      libelle: "Cadre P5",            statut: "cadres",               salaireMinima: 348720 },
    ],
  },
  {
    id: "CC007", nom: "SECURITE_PRIVEE", secteur: "Sécurité Privée", dateSignature: "1995-01-01",
    description: "Convention collective du secteur de la sécurité privée au Sénégal.",
    categories: [
      { id: "sp1",  code: "1er",      libelle: "1er Employé",     statut: "employés",             salaireMinima: 74870 },
      { id: "sp2",  code: "2ème_A",   libelle: "2ème A",          statut: "employés",             salaireMinima: 75361 },
      { id: "sp3",  code: "2ème_B",   libelle: "2ème B",          statut: "employés",             salaireMinima: 76461 },
      { id: "sp4",  code: "2ème_C",   libelle: "2ème C",          statut: "employés",             salaireMinima: 77561 },
      { id: "sp5",  code: "3ème_A",   libelle: "3ème A",          statut: "employés",             salaireMinima: 77840 },
      { id: "sp6",  code: "3ème_B",   libelle: "3ème B",          statut: "employés",             salaireMinima: 78940 },
      { id: "sp7",  code: "3ème_C",   libelle: "3ème C",          statut: "employés",             salaireMinima: 80040 },
      { id: "sp8",  code: "4ème_A",   libelle: "4ème A",          statut: "employés",             salaireMinima: 82272 },
      { id: "sp9",  code: "4ème_B",   libelle: "4ème B",          statut: "employés",             salaireMinima: 83050 },
      { id: "sp10", code: "4ème_C",   libelle: "4ème C",          statut: "employés",             salaireMinima: 84150 },
      { id: "sp11", code: "5ème_A",   libelle: "5ème A",          statut: "employés",             salaireMinima: 89244 },
      { id: "sp12", code: "5ème_B",   libelle: "5ème B",          statut: "employés",             salaireMinima: 90324 },
      { id: "sp13", code: "5ème_C",   libelle: "5ème C",          statut: "employés",             salaireMinima: 91404 },
      { id: "sp14", code: "6ème_A",   libelle: "6ème A",          statut: "employés",             salaireMinima: 93790 },
      { id: "sp15", code: "6ème_B",   libelle: "6ème B",          statut: "employés",             salaireMinima: 95494 },
      { id: "sp16", code: "6ème_C",   libelle: "6ème C",          statut: "employés",             salaireMinima: 97200 },
      { id: "sp17", code: "7ème_A",   libelle: "7ème A",          statut: "agents de maîtrise",   salaireMinima: 110160 },
      { id: "sp18", code: "7ème_B",   libelle: "7ème B",          statut: "agents de maîtrise",   salaireMinima: 113984 },
      { id: "sp19", code: "7ème_C",   libelle: "7ème C",          statut: "agents de maîtrise",   salaireMinima: 117342 },
      { id: "sp20", code: "8ème_A",   libelle: "8ème A",          statut: "agents de maîtrise",   salaireMinima: 120960 },
      { id: "sp21", code: "8ème_B",   libelle: "8ème B",          statut: "agents de maîtrise",   salaireMinima: 123660 },
      { id: "sp22", code: "8ème_C",   libelle: "8ème C",          statut: "agents de maîtrise",   salaireMinima: 127440 },
      { id: "sp23", code: "9ème_A",   libelle: "9ème A",          statut: "cadres",               salaireMinima: 127050 },
      { id: "sp24", code: "9ème_B",   libelle: "9ème B",          statut: "cadres",               salaireMinima: 139650 },
      { id: "sp25", code: "9ème_C",   libelle: "9ème C",          statut: "cadres",               salaireMinima: 153300 },
      { id: "sp26", code: "10ème_A",  libelle: "10ème A",         statut: "cadres",               salaireMinima: 168000 },
      { id: "sp27", code: "10ème_B",  libelle: "10ème B",         statut: "cadres",               salaireMinima: 173250 },
      { id: "sp28", code: "10ème_C",  libelle: "10ème C",         statut: "cadres",               salaireMinima: 180600 },
      { id: "sp29", code: "11ème_A",  libelle: "11ème A",         statut: "cadres",               salaireMinima: 195119 },
      { id: "sp30", code: "11ème_B",  libelle: "11ème B",         statut: "cadres",               salaireMinima: 198450 },
      { id: "sp31", code: "11ème_C",  libelle: "11ème C",         statut: "cadres",               salaireMinima: 204750 },
    ],
  },
  {
    id: "CC008", nom: "TRANSPORTS_PUBLICS_ROUTIERS", secteur: "Transports Publics Routiers", dateSignature: "1985-01-01",
    description: "Convention collective des transports publics routiers au Sénégal.",
    categories: [
      { id: "tpr1",  code: "A1",   libelle: "Personnel Roulant A1", statut: "personnel roulant",   salaireMinima: 77612 },
      { id: "tpr2",  code: "A2",   libelle: "Personnel Roulant A2", statut: "personnel roulant",   salaireMinima: 83477 },
      { id: "tpr3",  code: "B1",   libelle: "Personnel Roulant B1", statut: "personnel roulant",   salaireMinima: 83634 },
      { id: "tpr4",  code: "B2",   libelle: "Personnel Roulant B2", statut: "personnel roulant",   salaireMinima: 85040 },
      { id: "tpr5",  code: "C1",   libelle: "Personnel Roulant C1", statut: "personnel roulant",   salaireMinima: 85159 },
      { id: "tpr6",  code: "C2",   libelle: "Personnel Roulant C2", statut: "personnel roulant",   salaireMinima: 85542 },
      { id: "tpr7",  code: "D1",   libelle: "Personnel Roulant D1", statut: "personnel roulant",   salaireMinima: 88677 },
      { id: "tpr8",  code: "D2",   libelle: "Personnel Roulant D2", statut: "personnel roulant",   salaireMinima: 91522 },
      { id: "tpr9",  code: "1ère", libelle: "1ère Ouvrier",         statut: "ouvriers",             salaireMinima: 70709 },
      { id: "tpr10", code: "2ème", libelle: "2ème Ouvrier",         statut: "ouvriers",             salaireMinima: 72559 },
      { id: "tpr11", code: "3ème", libelle: "3ème Ouvrier",         statut: "ouvriers",             salaireMinima: 75901 },
      { id: "tpr12", code: "4ème", libelle: "4ème Ouvrier",         statut: "ouvriers",             salaireMinima: 80143 },
      { id: "tpr13", code: "5ème", libelle: "5ème Ouvrier",         statut: "ouvriers",             salaireMinima: 81143 },
      { id: "tpr14", code: "6ème", libelle: "6ème Ouvrier",         statut: "ouvriers",             salaireMinima: 86236 },
      { id: "tpr15", code: "7ème", libelle: "7ème Ouvrier",         statut: "ouvriers",             salaireMinima: 91928 },
      { id: "tpr16", code: "1ère Emp", libelle: "1ère Employé",     statut: "employés",             salaireMinima: 70686 },
      { id: "tpr17", code: "2ème Emp", libelle: "2ème Employé",     statut: "employés",             salaireMinima: 71676 },
      { id: "tpr18", code: "3ème Emp", libelle: "3ème Employé",     statut: "employés",             salaireMinima: 77468 },
      { id: "tpr19", code: "4ème Emp", libelle: "4ème Employé",     statut: "employés",             salaireMinima: 84335 },
      { id: "tpr20", code: "5ème Emp", libelle: "5ème Employé",     statut: "employés",             salaireMinima: 88511 },
      { id: "tpr21", code: "6ème Emp", libelle: "6ème Employé",     statut: "employés",             salaireMinima: 93329 },
      { id: "tpr22", code: "7ème Emp", libelle: "7ème Employé",     statut: "employés",             salaireMinima: 103350 },
      { id: "tpr23", code: "M1",   libelle: "Maîtrise 1",          statut: "agents de maîtrise",   salaireMinima: 104413 },
      { id: "tpr24", code: "M2",   libelle: "Maîtrise 2",          statut: "agents de maîtrise",   salaireMinima: 105477 },
      { id: "tpr25", code: "M3",   libelle: "Maîtrise 3",          statut: "agents de maîtrise",   salaireMinima: 125532 },
      { id: "tpr26", code: "M4",   libelle: "Maîtrise 4",          statut: "agents de maîtrise",   salaireMinima: 138513 },
      { id: "tpr27", code: "M5",   libelle: "Maîtrise 5",          statut: "agents de maîtrise",   salaireMinima: 139751 },
    ],
  },
  {
    id: "CC009", nom: "PETROLE_ET_GAZ", secteur: "Pétrole et Gaz", dateSignature: "2000-01-01",
    description: "Convention collective du secteur pétrole et gaz au Sénégal.",
    categories: [
      { id: "pg1",  code: "O1",     libelle: "Ouvrier O1",          statut: "ouvriers",             salaireMinima: 142299 },
      { id: "pg2",  code: "O2",     libelle: "Ouvrier O2",          statut: "ouvriers",             salaireMinima: 164330 },
      { id: "pg3",  code: "OS1A",   libelle: "Ouvrier Spéc. 1A",    statut: "ouvriers",             salaireMinima: 166501 },
      { id: "pg4",  code: "OS1B",   libelle: "Ouvrier Spéc. 1B",    statut: "ouvriers",             salaireMinima: 170813 },
      { id: "pg5",  code: "OS2A",   libelle: "Ouvrier Spéc. 2A",    statut: "ouvriers",             salaireMinima: 171306 },
      { id: "pg6",  code: "OS2B",   libelle: "Ouvrier Spéc. 2B",    statut: "ouvriers",             salaireMinima: 171798 },
      { id: "pg7",  code: "OS2C",   libelle: "Ouvrier Spéc. 2C",    statut: "ouvriers",             salaireMinima: 173197 },
      { id: "pg8",  code: "OP1",    libelle: "Ouvrier Principal 1",  statut: "ouvriers",             salaireMinima: 174594 },
      { id: "pg9",  code: "OP2",    libelle: "Ouvrier Principal 2",  statut: "ouvriers",             salaireMinima: 198321 },
      { id: "pg10", code: "OP3A",   libelle: "Ouvrier Principal 3A", statut: "ouvriers",             salaireMinima: 207520 },
      { id: "pg11", code: "OP3B",   libelle: "Ouvrier Principal 3B", statut: "ouvriers",             salaireMinima: 250734 },
      { id: "pg12", code: "OP3C",   libelle: "Ouvrier Principal 3C", statut: "ouvriers",             salaireMinima: 266632 },
      { id: "pg13", code: "1 ère",  libelle: "1ère Employé",        statut: "employés",             salaireMinima: 136113 },
      { id: "pg14", code: "2 ème A",libelle: "2ème A Employé",      statut: "employés",             salaireMinima: 157186 },
      { id: "pg15", code: "2 ème B",libelle: "2ème B Employé",      statut: "employés",             salaireMinima: 159261 },
      { id: "pg16", code: "3 ème",  libelle: "3ème Employé",        statut: "employés",             salaireMinima: 163386 },
      { id: "pg17", code: "4 ème A",libelle: "4ème A Employé",      statut: "employés",             salaireMinima: 163863 },
      { id: "pg18", code: "4 ème B",libelle: "4ème B Employé",      statut: "employés",             salaireMinima: 164329 },
      { id: "pg19", code: "4 ème C",libelle: "4ème C Employé",      statut: "employés",             salaireMinima: 165668 },
      { id: "pg20", code: "5 ème",  libelle: "5ème Employé",        statut: "employés",             salaireMinima: 167002 },
      { id: "pg21", code: "6 ème",  libelle: "6ème Employé",        statut: "employés",             salaireMinima: 189698 },
      { id: "pg22", code: "7 ème A",libelle: "7ème A Employé",      statut: "employés",             salaireMinima: 198496 },
      { id: "pg23", code: "7 ème B",libelle: "7ème B Employé",      statut: "employés",             salaireMinima: 239832 },
      { id: "pg24", code: "7 ème C",libelle: "7ème C Employé",      statut: "employés",             salaireMinima: 255040 },
      { id: "pg25", code: "AM_1",   libelle: "Agent Maîtrise 1",   statut: "agents de maîtrise",   salaireMinima: 259982 },
      { id: "pg26", code: "AM_2",   libelle: "Agent Maîtrise 2",   statut: "agents de maîtrise",   salaireMinima: 284532 },
      { id: "pg27", code: "AM_3",   libelle: "Agent Maîtrise 3",   statut: "agents de maîtrise",   salaireMinima: 291835 },
      { id: "pg28", code: "AM_4",   libelle: "Agent Maîtrise 4",   statut: "agents de maîtrise",   salaireMinima: 309761 },
      { id: "pg29", code: "AM_5",   libelle: "Agent Maîtrise 5",   statut: "agents de maîtrise",   salaireMinima: 314598 },
      { id: "pg30", code: "P1A",    libelle: "Cadre P1A",           statut: "cadres",               salaireMinima: 316424 },
      { id: "pg31", code: "P1B",    libelle: "Cadre P1B",           statut: "cadres",               salaireMinima: 322618 },
      { id: "pg32", code: "P2A",    libelle: "Cadre P2A",           statut: "cadres",               salaireMinima: 334836 },
      { id: "pg33", code: "P2B",    libelle: "Cadre P2B",           statut: "cadres",               salaireMinima: 346692 },
      { id: "pg34", code: "P3A",    libelle: "Cadre P3A",           statut: "cadres",               salaireMinima: 358545 },
      { id: "pg35", code: "P3B",    libelle: "Cadre P3B",           statut: "cadres",               salaireMinima: 387360 },
      { id: "pg36", code: "P4A",    libelle: "Cadre P4A",           statut: "cadres",               salaireMinima: 417999 },
      { id: "pg37", code: "P4B",    libelle: "Cadre P4B",           statut: "cadres",               salaireMinima: 451556 },
      { id: "pg38", code: "P5",     libelle: "Cadre P5",            statut: "cadres",               salaireMinima: 487849 },
    ],
  },
  {
    id: "CC010", nom: "TRANSPORTS_ROUTIERS_HYDROCARBURES", secteur: "Transports Routiers d'Hydrocarbures", dateSignature: "1990-01-01",
    description: "Convention collective des transports routiers d'hydrocarbures au Sénégal.",
    categories: [
      { id: "trh1",  code: "C1",     libelle: "Chauffeur C1",        statut: "chauffeurs",           salaireMinima: 97325 },
      { id: "trh2",  code: "C2 A",   libelle: "Chauffeur C2 A",      statut: "chauffeurs",           salaireMinima: 97761 },
      { id: "trh3",  code: "C2 B",   libelle: "Chauffeur C2 B",      statut: "chauffeurs",           salaireMinima: 101345 },
      { id: "trh4",  code: "C2 C",   libelle: "Chauffeur C2 C",      statut: "chauffeurs",           salaireMinima: 104596 },
      { id: "trh5",  code: "1ère",   libelle: "1ère Ouvrier",        statut: "ouvriers",             salaireMinima: 78554 },
      { id: "trh6",  code: "2ème",   libelle: "2ème Ouvrier",        statut: "ouvriers",             salaireMinima: 80620 },
      { id: "trh7",  code: "3ème",   libelle: "3ème Ouvrier",        statut: "ouvriers",             salaireMinima: 84335 },
      { id: "trh8",  code: "4ème",   libelle: "4ème Ouvrier",        statut: "ouvriers",             salaireMinima: 91593 },
      { id: "trh9",  code: "5ème",   libelle: "5ème Ouvrier",        statut: "ouvriers",             salaireMinima: 92593 },
      { id: "trh10", code: "6ème",   libelle: "6ème Ouvrier",        statut: "ouvriers",             salaireMinima: 98555 },
      { id: "trh11", code: "7ème",   libelle: "7ème Ouvrier",        statut: "ouvriers",             salaireMinima: 105060 },
      { id: "trh12", code: "4ème Emp", libelle: "4ème Employé",      statut: "employés",             salaireMinima: 96382 },
      { id: "trh13", code: "5ème Emp", libelle: "5ème Employé",      statut: "employés",             salaireMinima: 101155 },
      { id: "trh14", code: "6ème Emp", libelle: "6ème Employé",      statut: "employés",             salaireMinima: 106662 },
      { id: "trh15", code: "7ème Emp", libelle: "7ème Employé",      statut: "employés",             salaireMinima: 118113 },
      { id: "trh16", code: "AM1",    libelle: "Maîtrise 1",         statut: "agents de maîtrise",   salaireMinima: 120075 },
      { id: "trh17", code: "AM2",    libelle: "Maîtrise 2",         statut: "agents de maîtrise",   salaireMinima: 120545 },
      { id: "trh18", code: "AM3",    libelle: "Maîtrise 3",         statut: "agents de maîtrise",   salaireMinima: 143465 },
      { id: "trh19", code: "AM4",    libelle: "Maîtrise 4",         statut: "agents de maîtrise",   salaireMinima: 158300 },
      { id: "trh20", code: "AM5",    libelle: "Maîtrise 5",         statut: "agents de maîtrise",   salaireMinima: 159716 },
      { id: "trh21", code: "P1",     libelle: "Cadre P1",           statut: "cadres",               salaireMinima: 165366 },
      { id: "trh22", code: "P2",     libelle: "Cadre P2",           statut: "cadres",               salaireMinima: 168977 },
      { id: "trh23", code: "P3. A",  libelle: "Cadre P3 A",         statut: "cadres",               salaireMinima: 179674 },
      { id: "trh24", code: "P3. B",  libelle: "Cadre P3 B",         statut: "cadres",               salaireMinima: 254098 },
    ],
  },
  {
    id: "CC011", nom: "INDUSTRIES_CHIMIQUES_EXTRATIVES_PROSPECTION_MINIERE", secteur: "Industries Chimiques, Extractives & Prospection Minière", dateSignature: "1985-01-01",
    description: "Convention collective des industries chimiques, extractives et de prospection minière au Sénégal.",
    categories: [
      { id: "ic1",  code: "1 ère M.O",    libelle: "1ère M.O",          statut: "ouvriers",             salaireMinima: 70709 },
      { id: "ic2",  code: "2 ème M.S",    libelle: "2ème M.S",          statut: "ouvriers",             salaireMinima: 72433 },
      { id: "ic3",  code: "3 ème O.S.1",  libelle: "3ème O.S.1",        statut: "ouvriers",             salaireMinima: 76015 },
      { id: "ic4",  code: "4 ème O.S.2",  libelle: "4ème O.S.2",        statut: "ouvriers",             salaireMinima: 79871 },
      { id: "ic5",  code: "5 ème O.P.1",  libelle: "5ème O.P.1",        statut: "ouvriers",             salaireMinima: 80871 },
      { id: "ic6",  code: "6 ème O.P.2",  libelle: "6ème O.P.2",        statut: "ouvriers",             salaireMinima: 87040 },
      { id: "ic7",  code: "7 ème O.P.3",  libelle: "7ème O.P.3",        statut: "ouvriers",             salaireMinima: 96051 },
      { id: "ic8",  code: "1ère",          libelle: "1ère Employé",      statut: "employés",             salaireMinima: 70688 },
      { id: "ic9",  code: "2ème",          libelle: "2ème Employé",      statut: "employés",             salaireMinima: 73695 },
      { id: "ic10", code: "3ème",          libelle: "3ème Employé",      statut: "employés",             salaireMinima: 77355 },
      { id: "ic11", code: "4ème",          libelle: "4ème Employé",      statut: "employés",             salaireMinima: 84148 },
      { id: "ic12", code: "5ème",          libelle: "5ème Employé",      statut: "employés",             salaireMinima: 87746 },
      { id: "ic13", code: "6ème",          libelle: "6ème Employé",      statut: "employés",             salaireMinima: 92733 },
      { id: "ic14", code: "7ème",          libelle: "7ème Employé",      statut: "employés",             salaireMinima: 103614 },
      { id: "ic15", code: "A.M.1",        libelle: "Agent Maîtrise 1",  statut: "agents de maîtrise",   salaireMinima: 109739 },
      { id: "ic16", code: "A.M.2",        libelle: "Agent Maîtrise 2",  statut: "agents de maîtrise",   salaireMinima: 115863 },
      { id: "ic17", code: "A.M.3",        libelle: "Agent Maîtrise 3",  statut: "agents de maîtrise",   salaireMinima: 125315 },
      { id: "ic18", code: "A.M.4",        libelle: "Agent Maîtrise 4",  statut: "agents de maîtrise",   salaireMinima: 137387 },
      { id: "ic19", code: "A.M.5",        libelle: "Agent Maîtrise 5",  statut: "agents de maîtrise",   salaireMinima: 139750 },
    ],
  },
];

export const EMPTY_EMPLOYEE: Employee = {
  matricule: "", prenom: "", nom: "", sexe: "M",
  dateNaissance: "", lieuNaissance: "", nationalite: "Sénégalaise",
  adresse: "", telephone: "", email: "", situationFamille: "Célibataire",
  femmes: 0, enfants: 0, fonction: "", convention: "COMMERCE",
  categorie: "", statut: "employés", contrat: "CDI",
  dateEntree: "", salaireBase: 0, sursalaire: 0,
  heuresAbsence: 0, heuresAbsMaladie: 0, tauxMaladie: 0, nbPaniers: 0,
  hs115: 0, hs140: 0, hs160: 0, hs200: 0,
  avanceTabaski: 0, avanceCaisse: 0, avanceFinanciere: 0, retCooperative: 0, fraisMedicaux: 0, indKilometrique: 0,
};

export const STATUT_COLORS: Record<string, string> = {
  "employés": "senpaie-blue",
  "agents de maîtrise": "senpaie-yellow",
  "cadres": "senpaie-purple",
  "ouvriers": "primary",
  "personnel roulant": "senpaie-blue",
  "chauffeurs": "senpaie-yellow",
  "prestataires": "primary",
};

export type TabId = "dashboard" | "employes" | "cotisations" | "tendances" | "simulateur" | "conventions" | "entreprise" | "parametres";

export const NAV_ITEMS: { id: TabId; icon: string; label: string }[] = [
  { id: "dashboard",    icon: "◈",  label: "Tableau de bord" },
  { id: "employes",     icon: "◎",  label: "Employés" },
  { id: "cotisations",  icon: "◉",  label: "Cotisations" },
  { id: "tendances",    icon: "∿",  label: "Tendances" },
  { id: "simulateur",   icon: "⊕",  label: "Simulateur" },
  { id: "conventions",  icon: "📋", label: "Conventions" },
  { id: "entreprise",   icon: "🏢", label: "Entreprise" },
  { id: "parametres",   icon: "⚙",  label: "Paramètres" },
];
