import type { Employee } from "./payroll";

/** Préfixe réservé aux employés de démonstration — permet une suppression en 1 clic. */
export const DEMO_PREFIX = "DEMO-";

const base = {
  sexe: "M" as const,
  lieuNaissance: "Dakar",
  nationalite: "Sénégalaise",
  adresse: "Dakar, Sénégal",
  situationFamille: "Marié(e)",
  femmes: 1,
  enfants: 2,
  convention: "COMMERCE",
  contrat: "CDI",
  heuresAbsence: 0,
  heuresAbsMaladie: 0,
  tauxMaladie: 100,
  nbPaniers: 0,
  hs115: 0,
  hs140: 0,
  hs160: 0,
  hs200: 0,
  avanceTabaski: 0,
  avanceCaisse: 0,
  avanceFinanciere: 0,
  retCooperative: 0,
  fraisMedicaux: 0,
  indKilometrique: 0,
};

export const DEMO_EMPLOYEES: Employee[] = [
  {
    ...base,
    matricule: `${DEMO_PREFIX}001`,
    prenom: "Awa",
    nom: "Diallo",
    sexe: "F",
    dateNaissance: "1988-04-12",
    telephone: "770000001",
    email: "awa.diallo@exemple.sn",
    femmes: 0,
    enfants: 3,
    fonction: "Directrice Administrative",
    categorie: "Cadre",
    statut: "Cadre",
    dateEntree: "2015-01-05",
    salaireBase: 850000,
    sursalaire: 150000,
  },
  {
    ...base,
    matricule: `${DEMO_PREFIX}002`,
    prenom: "Moussa",
    nom: "Ndiaye",
    dateNaissance: "1990-09-23",
    telephone: "770000002",
    email: "moussa.ndiaye@exemple.sn",
    fonction: "Comptable",
    categorie: "Agent de maîtrise",
    statut: "Agent de maîtrise",
    dateEntree: "2018-03-01",
    salaireBase: 320000,
    sursalaire: 40000,
  },
  {
    ...base,
    matricule: `${DEMO_PREFIX}003`,
    prenom: "Fatou",
    nom: "Sarr",
    sexe: "F",
    dateNaissance: "1995-02-17",
    telephone: "770000003",
    email: "fatou.sarr@exemple.sn",
    situationFamille: "Célibataire",
    femmes: 0,
    enfants: 0,
    fonction: "Assistante commerciale",
    categorie: "Employé",
    statut: "Employé",
    dateEntree: "2021-06-14",
    salaireBase: 150000,
    sursalaire: 0,
    nbPaniers: 4,
  },
  {
    ...base,
    matricule: `${DEMO_PREFIX}004`,
    prenom: "Ibrahima",
    nom: "Fall",
    dateNaissance: "1983-11-02",
    telephone: "770000004",
    email: "ibrahima.fall@exemple.sn",
    fonction: "Magasinier",
    categorie: "Ouvrier",
    statut: "Ouvrier",
    contrat: "CDD",
    dateEntree: "2023-02-01",
    salaireBase: 95000,
    sursalaire: 0,
    hs115: 8,
    hs140: 4,
  },
  {
    ...base,
    matricule: `${DEMO_PREFIX}005`,
    prenom: "Seynabou",
    nom: "Gueye",
    sexe: "F",
    dateNaissance: "1992-07-30",
    telephone: "770000005",
    email: "seynabou.gueye@exemple.sn",
    femmes: 0,
    enfants: 1,
    fonction: "Chargée de clientèle",
    categorie: "Employé",
    statut: "Employé",
    dateEntree: "2020-10-12",
    salaireBase: 210000,
    sursalaire: 25000,
    avanceCaisse: 20000,
  },
];

export const isDemoEmployee = (matricule: string) => matricule.startsWith(DEMO_PREFIX);
